# Generated by Django 3.0.6 on 2020-07-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200723_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='level',
            name='major',
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ManyToManyField(to='website.Level'),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='major',
        ),
        migrations.AddField(
            model_name='courses',
            name='major',
            field=models.ManyToManyField(to='website.Major'),
        ),
        migrations.CreateModel(
            name='Courses_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='term',
            field=models.ManyToManyField(to='website.Terms'),
        ),
    ]
