# Generated by Django 3.0.6 on 2020-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200725_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='level',
        ),
        migrations.AddField(
            model_name='terms',
            name='levels',
            field=models.ManyToManyField(to='website.Level'),
        ),
    ]
