# Generated by Django 3.0.6 on 2020-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200725_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='major',
        ),
        migrations.AddField(
            model_name='level',
            name='major',
            field=models.ManyToManyField(to='website.Major'),
        ),
    ]
