# Generated by Django 3.0.6 on 2020-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200725_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='term',
        ),
        migrations.DeleteModel(
            name='Terms',
        ),
    ]
