    # Generated by Django 3.0.6 on 2020-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activitie_disc',
            field=models.TextField(null=True),
        ),
    ]
