# Generated by Django 3.0.6 on 2020-07-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_major_major_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Courses_image',
            new_name='Course_image',
        ),
    ]
