# Generated by Django 3.0.6 on 2020-08-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_courses_course_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['course_name']},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_num',
        ),
        migrations.RemoveField(
            model_name='courses_files',
            name='lecture_name',
        ),
    ]
