# Generated by Django 3.0.6 on 2020-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200802_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_image',
            field=models.ImageField(null=True, upload_to='major_pic'),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_image',
            field=models.ImageField(null=True, upload_to='major_pic'),
        ),
    ]
