# Generated by Django 3.0.6 on 2020-08-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_files',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Teacher'),
        ),
    ]
