# Generated by Django 3.0.6 on 2020-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_courses_files_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(null=True, upload_to='teacher'),
        ),
    ]
