# Generated by Django 3.0.6 on 2020-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20200928_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsvideos',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
