# Generated by Django 3.0.6 on 2020-09-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20200928_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialsvideos',
            options={},
        ),
        migrations.RemoveField(
            model_name='tutorialsvideos',
            name='pub_date',
        ),
    ]
