# Generated by Django 3.0.6 on 2020-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20200928_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_files',
            name='lecture_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses_files',
            name='lecture_url',
            field=models.FileField(upload_to='Lectures'),
        ),
    ]
