# Generated by Django 3.0.6 on 2020-10-09 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0046_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_files',
            name='user',
        ),
        migrations.AddField(
            model_name='tutorialsteacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
