# Generated by Django 3.0.6 on 2020-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_remove_tutorialsteacher_videos_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsvideos',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
