# Generated by Django 3.0.6 on 2020-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_auto_20201011_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activitie_name',
            field=models.CharField(max_length=50),
        ),
    ]
