# Generated by Django 3.1.2 on 2020-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_courses_files_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to='website.Teacher'),
        ),
    ]
