# Generated by Django 4.0.5 on 2022-11-15 19:39

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create(
        [
            Group(name="teacher"),
            Group(name="admin"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0065_auto_20220701_0224"),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
