# Generated by Django 3.0.6 on 2020-07-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage_system.Level')),
            ],
        ),
    ]
