# Generated by Django 3.0.6 on 2020-07-23 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0003_courses_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collage_system.Major'),
        ),
    ]
