# Generated by Django 3.0.6 on 2020-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0005_auto_20200723_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_files',
            name='file',
            field=models.FileField(upload_to='courses'),
        ),
    ]
