# Generated by Django 3.0.6 on 2020-07-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0006_auto_20200723_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='term',
        ),
        migrations.AddField(
            model_name='courses',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collage_system.Terms'),
        ),
    ]
