# Generated by Django 3.0.6 on 2020-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0008_auto_20200723_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Courses_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
