# Generated by Django 3.0.6 on 2020-07-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0009_courses_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collage_system.Major'),
        ),
    ]
