# Generated by Django 3.0.6 on 2020-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0011_terms_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='level',
        ),
        migrations.AddField(
            model_name='terms',
            name='level',
            field=models.ManyToManyField(null=True, to='collage_system.Level'),
        ),
    ]
