# Generated by Django 3.0.6 on 2020-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0017_auto_20200726_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ManyToManyField(null=True, to='collage_system.Level'),
        ),
    ]
