# Generated by Django 3.0.6 on 2020-07-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0018_auto_20200726_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collage_system.Level'),
        ),
    ]
