# Generated by Django 3.0.6 on 2020-07-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0019_auto_20200726_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='major',
        ),
    ]
