# Generated by Django 3.0.6 on 2020-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0021_auto_20200727_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitie_name', models.CharField(max_length=100)),
                ('activitie_image', models.ImageField(upload_to='Activities')),
            ],
        ),
    ]
