# Generated by Django 3.0.6 on 2020-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0026_auto_20200730_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_files',
            name='lecture_url',
            field=models.FileField(upload_to=''),
        ),
    ]
