# Generated by Django 3.0.6 on 2020-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0027_auto_20200730_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_num',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
