# Generated by Django 3.0.6 on 2020-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0034_tutorials_tutorialsteacher_tutorialsvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsteacher',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
