# Generated by Django 3.0.6 on 2020-09-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0035_tutorialsteacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsvideos',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
