# Generated by Django 3.0.6 on 2020-09-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0036_tutorialsvideos_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsvideos',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
