# Generated by Django 3.0.6 on 2020-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0039_auto_20200928_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsvideos',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
