# Generated by Django 3.0.6 on 2020-10-11 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0049_tutorialsvideos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activitie_create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tutorialsteacher',
            name='tutorials_image',
            field=models.ImageField(blank=True, null=True, upload_to='TutorialsTeacher'),
        ),
    ]
