# Generated by Django 3.0.6 on 2020-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0051_auto_20201011_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activitie_image1',
            field=models.ImageField(blank=True, null=True, upload_to='Activities'),
        ),
        migrations.AddField(
            model_name='activities',
            name='activitie_image2',
            field=models.ImageField(blank=True, null=True, upload_to='Activities'),
        ),
    ]
