# Generated by Django 3.0.6 on 2020-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0053_courses_files_add_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['-activitie_create_date']},
        ),
        migrations.AlterModelOptions(
            name='courses_files',
            options={'ordering': ['-add_date']},
        ),
        migrations.AddField(
            model_name='activities',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
