# Generated by Django 3.0.6 on 2020-10-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0054_auto_20201014_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='slug',
        ),
    ]
