# Generated by Django 3.0.6 on 2020-10-16 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0055_remove_activities_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activitie_create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
