# Generated by Django 3.0.6 on 2020-10-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0057_auto_20201030_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
