# Generated by Django 3.1.2 on 2020-11-05 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0058_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggAndComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.CharField(max_length=30)),
                ('sugg_dics', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['-major_name']},
        ),
        migrations.AlterField(
            model_name='tutorialsvideos',
            name='video',
            field=models.FileField(upload_to='VideoTutorials0000000000000'),
        ),
    ]
