# Generated by Django 3.1.2 on 2020-11-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0059_auto_20201105_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activitie_create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='courses_files',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='suggandcomp',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
