# Generated by Django 3.1.2 on 2020-11-14 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0060_auto_20201109_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_file', models.FileField(upload_to='programs')),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
