# Generated by Django 3.1.2 on 2020-11-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0062_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_files',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collage_system.student'),
        ),
    ]
