# Generated by Django 3.0.6 on 2022-07-01 02:24

from django.db import migrations

major_defaults = [
        {
            'name': 'Computer Science',
            'file': 'major_pic/cs.png',
            'slug': 'cs'
        },
        {
            'name': 'Information Technology',
            'file': 'major_pic/it.png',
            'slug': 'it'
        }
    ]

semester_defaults = [
    {
        'name': '1',
        'file': 'major_pic/s1.png'
    },
    {
        'name': '2',
        'file': 'major_pic/s2.png'
    }
]


level_default = [
    {
        'level': 1,
        'file': 'major_pic/l1.png',
    },
    {
        'level': 2,
        'file': 'major_pic/l2.png',
    },
    {
        'level': 3,
        'file': 'major_pic/l3.png',
    },
    {
        'level': 4,
        'file': 'major_pic/l4.png',
    }
]


def inital_values(apps, schema_editor):
    Major = apps.get_model('collage_system', 'Major')
    Semster = apps.get_model('collage_system', 'Semester')
    Level = apps.get_model('collage_system', 'Level')

    for major in major_defaults:
        thisMajor = Major(major_name=major['name'], major_image=major['file'], slug=major['slug'])
        thisMajor.save()

    for level in level_default:
        thisLevel = Level(level=level['level'], level_image=level['file'])
        thisLevel.save()

    for semester in semester_defaults:
        thisSemester = Semster(semester=semester['name'], semester_image=semester['file'])
        thisSemester.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('collage_system', '0064_auto_20201122_0957'),
    ]

    operations = [
     migrations.RunPython(inital_values)   
    ]
